fullnameOverride: "external-dns-unifi"

logLevel: debug
logFormat: text

interval: 1m
triggerLoopOnEvent: false

namespaced: false

domainFilters:
- local.damman.tech

sources:
- crd
- service
- ingress
- gateway-httproute

policy: sync

registry: noop
txtOwnerId: "default"
txtPrefix: "talos."
txtSuffix: ""

provider:
  name: webhook
  webhook:
    image:
      repository: 'ghcr.io/kashalls/external-dns-unifi-webhook'
      tag: main
      pullPolicy: IfNotPresent
    env:
    - name: UNIFI_HOST
      value: https://10.0.10.193
    - name: UNIFI_EXTERNAL_CONTROLLER
      value: "false"
    - name: UNIFI_API_KEY
      valueFrom:
        secretKeyRef:
          name: external-dns-unifi-secret
          key: api-key
    - name: LOG_LEVEL
      value: info
    livenessProbe:
      httpGet:
        path: /healthz
        port: http-webhook
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 2
      successThreshold: 1
    readinessProbe:
      httpGet:
        path: /healthz
        port: http-webhook
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
    service:
      port: 8080

tolerations:
- key: node-role.kubernetes.io/control-plane
  operator: Equal
  value: "true"
  effect: NoSchedule

extraArgs:
- --ignore-ingress-tls-spec
