version: 2
updates:
  - package-ecosystem: "helm"
    directory: "/resources/gitops-config/sync-app/templates"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/resources/gitops-config"
    schedule:
      interval: "weekly"
