configs:
  cm:
    url: https://argocd.local.damman.tech
    exec.enabled: true
    admin.enabled: true
    resource.exclusions: "[{apiGroups: ['cilium.io'], kinds: ['CiliumIdentity'], clusters: ['*']}]"
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientSecret: $github-client-secret:dex.github.clientSecret
            clientID: 73cf0e66844d5dd766ab
            orgs:
              - name: sironite
                teams:
                  - DevOps
  params:
    server.insecure: true
  rbac:
    policy.csv: |
      g, sironite:DevOps, role:admin
    policy.default: role:readonly

controller:
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    value: "true"
    effect: NoSchedule
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 1Gi

applicationSet:
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    value: "true"
    effect: NoSchedule
  resources:
    limits:
      cpu: 1
      memory: 100Mi
    requests:
      cpu: 2m
      memory: 50Mi

repoServer:
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    value: "true"
    effect: NoSchedule
  resources:
    limits:
      cpu: 1
      memory: 400Mi
    requests:
      cpu: 10m
      memory: 100Mi

server:
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    value: "true"
    effect: NoSchedule
  resources:
    limits:
      cpu: 1
      memory: 300Mi
    requests:
      cpu: 2m
      memory: 75Mi
  insecure: true

redis:
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    value: "true"
    effect: NoSchedule
  resources:
    limits:
      cpu: 1
      memory: 50Mi
    requests:
      cpu: 1m
      memory: 20Mi

dex:
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    value: "true"
    effect: NoSchedule
  resources:
    limits:
      cpu: 1
      memory: 100Mi
    requests:
      cpu: 1m
      memory: 50Mi

notificationsController:
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    value: "true"
    effect: NoSchedule
  resources:
    limits:
      cpu: 1
      memory: 100Mi
    requests:
      cpu: 1m
      memory: 50Mi
