---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
spec:
  provider:
    onepassword:
      connectHost: 'http://onepassword-connect.onepassword:8080'
      vaults:
        KubernetesSecrets: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token-external-secret
            key: onepassword-connect-token
            namespace: external-secrets

