extraArgs:
  - --enable-gateway-api
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=1.1.1.1:53

global:
  leaderElection:
    namespace: cert-manager

podDnsConfig:
  nameservers:
    - 1.1.1.1
    - 8.8.8.8

crds:
  enabled: true
