---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-httproute
spec:
  parentRefs:
  - name: svc-gateway
    namespace: kube-system
    sectionName: svc-https-listener
  hostnames:
    - argocd.svc.damman.tech
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argo-cd-argocd-server
          port: 443