---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-private-homelab-config-creds
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: github-private-homelab-config-creds
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: https://github.com/TheIronRock95/homelab-config.git
        githubAppID: "1225477"
        githubAppInstallationID: "65046796"
        githubAppPrivateKey: '{{ `{{ .argoPrivateKey }}` }}'
  data:
  - secretKey: argoPrivateKey
    remoteRef:
      key: github-argo-app
      property: argocd-private-acces.2025-04-22.private-key.pem
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-private-homelab-apps-creds
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: github-private-homelab-apps-creds
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: https://github.com/TheIronRock95/homelab-apps.git
        githubAppID: "1225477"
        githubAppInstallationID: "65046796"
        githubAppPrivateKey: '{{ `{{ .argoPrivateKey }}` }}'
  data:
  - secretKey: argoPrivateKey
    remoteRef:
      key: github-argo-app
      property: argocd-private-acces.2025-04-22.private-key.pem