---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: onepassword-connect-credentials
  namespace: onepassword
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    name: onepassword-connect-credentials
    template:
      engineVersion: v2
      type: Opaque
      data:
        onepassword-connect-credentials.json: '{{ .credentials }}'
  data:
  - secretKey: credentials
    remoteRef:
      key: onepassword-connect-credentials.json
      property: password