connect:
  credentialsName: onepassword-connect-credentials
  credentialsKey: onepassword-connect-credentials.json

tolerations:
- key: node-role.kubernetes.io/control-plane
  operator: Equal
  value: "true"
  effect: NoSchedule

    