- op: add
  path: /spec/template/spec/tolerations
  value:
    - key: node-role.kubernetes.io/control-plane
      operator: Equal
      value: "true"
      effect: NoSchedule
      
- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 1Gi