# https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.local.damman.tech
  exec.enabled: "true"
  admin.enabled: "false"
  kustomize.buildOptions: --enable-helm
  resource.exclusions: |
    - apiGroups:
      - cilium.io
      kinds:
      - CiliumIdentity
      clusters:
      - "*"
  dex.config: |
    logger:
      level: debug
      format: json
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientSecret: $github-client-secret:dex.github.clientSecret
          clientID: 73cf0e66844d5dd766ab
          orgs:
          - name: sironite
            teams:           
            - DevOps

          