---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: argo-cd
  namespace: argocd
  labels:
    component: operators
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 7.8.15
      helm:
        valueFiles:
        - $values/resources/gitops-config/operators/argo-cd/values.yaml
    - repoURL: https://github.com/TheIronRock95/homelab-config
      path: resources/gitops-config/operators/argo-cd
      targetRevision: HEAD
      ref: values
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
