---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations: {}
  name: argo-cd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm/
      chart: argo-cd
      targetRevision: 8.0.14
      helm:
        valueFiles:
        - $values/resources/gitops-config/operators/argo-cd/values.yaml
    - repoURL: https://github.com/TheIronRock95/homelab-config
      targetRevision: HEAD
      path: resources/gitops-config/operators/argo-cd
      ref: values
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
