---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    component: operators
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-apps
    targetRevision: 2.0.2
    helm:
      values: |
        projects:
          operators:
            namespace: argocd
            displayName: Operators
            finalizers:
              - resources-finalizer.argocd.argoproj.io
            clusterResourceWhitelist:
            - group: '*'
              kind: '*'
            destinations:
            - namespace: '*'
              server: '*'
            sourceRepos:
            - '*'
          apps:
            namespace: argocd
            displayName: Apps
            finalizers:
              - resources-finalizer.argocd.argoproj.io
            clusterResourceWhitelist:
            - group: '*'
              kind: '*'
            destinations:
            - namespace: '*'
              server: '*'
            sourceRepos
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
