---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: argo-helm
  namespace: argocd 
  labels:
    component: operators
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo
    targetRevision: 2.0.2
    helm:
      values: |
        projects:
        operators:
            namespace: argocd
            finalizers:
            - resources-finalizer.argocd.argoproj.io
        applications:
            namespace: argocd
            finalizers:
            - resources-finalizer.argocd.argoproj.io
  destination:
    server: https://kubernetes.default.svc
    namespace: onepassword
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true