---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: cilium
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: operators
  sources:
    - repoURL: https://helm.cilium.io/
      chart: cilium
      targetRevision: 1.17.3
      helm:
        valueFiles:
        - $values/resources/gitops-config/operators/cilium/values.yaml
    - repoURL: https://github.com/TheIronRock95/homelab-config
      targetRevision: HEAD
      path: resources/gitops-config/operators/cilium
      ref: values
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
