---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: external-secrets
  namespace: argocd
  labels:
    component: operators
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
#   sources:
#     - repoURL: https://charts.external-secrets.io
#       chart: external-secrets
#       targetRevision: 0.14.2
#       helm:
#       helm:
#         values: |
#           installCRDs: true
#           tolerations:
#           - key: node-role.kubernetes.io/control-plane
#             operator: Equal
#             value: "true"
#             effect: NoSchedule

#     #     valueFiles:
#     #       - $values/resources/gitops-config/operators/external-secrets/values.yaml
    - repoURL: https://github.com/TheIronRock95/homelab-config
      targetRevision: HEAD
      path: resources/gitops-config/operators/external-secrets
      # ref: values
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      