---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: home-assistant
  namespace: argocd
  labels:
    component: operators
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  sources:
  - repoURL: 'http://pajikos.github.io/home-assistant-helm-chart'
    chart: home-assistant
    targetRevision: 0.2.119
    helm:
      valueFiles:
      - $values/apps/home_assistant/values.yaml
  - repoURL: https://github.com/TheIronRock95/homelab-apps
    targetRevision: HEAD
    path: apps/home_assistant
    ref: values
  destination:
    namespace: home-assistant
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
