---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: mariadb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  sources:
  - repoURL: https://groundhog2k.github.io/helm-charts/
    chart: mariadb
    targetRevision: 4.4.0
    helm:
      valueFiles:
      - $values/apps/mariadb/values.yaml
  - repoURL: https://github.com/TheIronRock95/homelab-apps
    targetRevision: HEAD
    path: apps/mariadb
    ref: values
  destination:
    namespace: mariadb
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
