---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: onepassword
  namespace: argocd 
  labels:
    component: operators
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: operators
  source:
    repoURL:'https://1password.github.io/connect-helm-charts/'
    chart: connect
    targetRevision: 1.17.0
    helm:
      values: |
        connect:
          credentialsName: onepassword-connect-credentials
          credentialsKey: onepassword-connect-credentials.json
        tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Equal
          value: "true"
          effect: NoSchedule
  destination:
    server: https://kubernetes.default.svc
    namespace: onepassword
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true