---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TheIronRock95/homelab-config
    path: resources/gitops-config/sync-app/templates/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true