zwavejs2mqtt:
  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #

  image:
    # -- image repository
    repository: zwavejs/zwavejs2mqtt
    # -- image tag
    tag: 9.30.1
    # -- image pull policy
    pullPolicy: IfNotPresent

  # -- environment variables. See [image docs](https://zwave-js.github.io/zwavejs2mqtt/#/guide/env-vars) for more details.
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: Europe/Amsterdam


  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          port: 8091
        websocket:
          enabled: true
          port: 3000

  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      enabled: true
      hosts:
      - host: zwave.local.damman.tech
        paths:
          - path: /
            pathType: Prefix
      annotations:
        kubernetes.io/ingress.class: traefik-internal
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        cert-manager.io/cluster-issuer: letsencrypt-production
      tls:
        - secretName: zwave.local.damman.tech-tls 
          hosts:
            - zwave.local.damman.tech
            
  tolerations:
  - key: usbservices
    operator: Equal
    value: "true"
    effect: NoSchedule

  securityContext:
    # -- (bool) Privileged securityContext may be required if USB devices are accessed directly through the host machine
    privileged: true

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    config:
      enabled: true
      size: 2Gi
      mountPath: /usr/src/app/store
    # -- Configure a hostPathMount to mount a USB device in the container.
    # @default -- See values.yaml
    # usb:
    #   enabled: true
    #   type: hostPath
    #   hostPath: /dev/serial/by-id/usb-0658_0200-if00

  additionalVolumeMounts:
    - name: usb
      mountPath: /dev/serial/by-id/usb-0658_0200-if00

  additionalVolumes:
    - name: usb
      hostPath:
        path: /dev/serial/by-id/usb-0658_0200-if00

  # -- Affinity constraint rules to place the Pod on a specific node.
  # [[ref]](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - dmn-pi-worker-01


