---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
# Secretes-controllers
- external-secrets.yaml
- onepassword-connect.yaml
# networking
- cilium.yaml
# ACME-controllers
- cert-manager.yaml
# DNS-controllers
- external-dns-internal.yaml
# Storage-controllers
# - nfs-provisioner.yaml
# Node-management
# - kured.yaml
# Monitoring
# - kube-prometheus-stack.yaml
