---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-2xdaily
  namespace: longhorn-system
spec:
  cron: "0 2,14 * * *"
  task: "backup"
  retain: 7
  concurrency: 1
  groups:
    - default
  labels: {}

---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-hourly
  namespace: longhorn-system
spec:
  cron: "0 * * * *"
  task: "snapshot"
  retain: 24
  concurrency: 1
  groups:
    - default
  labels: {}
