---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-2xdaily
  namespace: longhorn-system
spec:
  name: backup-2xdaily
  task: backup
  cron: "0 2,14 * * *"
  retain: 7
  concurrency: 1
  groups:
    - default
  labels: {}

---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-hourly
  namespace: longhorn-system
spec:
  name: snapshot-hourly
  task: snapshot
  cron: "0 * * * *"
  retain: 24
  concurrency: 1
  groups:
    - default
  labels: {}
