apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.deployment.name }}
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicaCount | default 1 }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit | default 0 }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      restartPolicy: {{ .Values.deployment.restartPolicy }}
      containers:
      - image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        name: {{ .Values.deployment.name }}
        volumeMounts:
        {{- range .Values.deployment.volumes }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
        {{- end }}
        {{- if .Values.deployment.lifecycle }}
        lifecycle:
          {{- .Values.deployment.lifecycle | toYaml | nindent 10}}
        {{- end }}
      volumes:
      {{- range .Values.deployment.volumes }}
      {{- if .configMap }}
      - name: {{ .name }}
        configMap:
          name: {{ .configMap.name }}
          items: {{ .configMap.items | toYaml | nindent 12 }}        
      {{- end }}
      {{- if .secret }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secret.name }}
      {{- end }}
      {{- if .claimName }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .claimName }}
      {{- end }}
      {{- end }}