{{ range .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  refreshInterval: {{ .refreshInterval }}
  secretStoreRef:
    name: {{ .storeName }}
    kind: ClusterSecretStore
  target:
    name: {{ .targetName }}
    template:
      engineVersion: v2
      templateFrom:
      - configMap:
          name: {{ .templateName }}
          items: {{ .templateItems | toYaml | nindent 12 }}
  data:
  {{- range .data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ .remoteRef.key }}
      property: {{ .remoteRef.property }}
  {{- end }}
---
{{ end }}