apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.httproute.name }}
spec:
  hostnames: {{ .Values.httproute.hostnames | toYaml | nindent 4 }}
  parentRefs:
  - name: {{ .Values.httproute.parentRef.name }}
    namespace: {{ .Values.httproute.parentRef.namespace }}
    sectionName: {{ .Values.httproute.parentRef.sectionName }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}