deployment:
  name: evcc
  restartPolicy: Always
  replicaCount: 1
  image:
    repository: evcc/evcc
    tag: 0.133.0
    pullPolicy: IfNotPresent
  volumes:
    - name: evcc-data
      mountPath: /root/.evcc
      claimName: evcc-data
    - name: evcc-secret
      mountPath: /etc/evcc/
      secret:
        name: evcc-secret
  securityContext:
    runAsUser: 30000
    allowPrivilegeEscalation: false
  lifecycle:
    postStart:
      exec:
        command:
          - /bin/sh
          - -c
          - cp /etc/evcc/evcc.yaml /etc/evcc.yaml

service:
  name: evcc-service
  type: ClusterIP
  port: 80
  targetPort: 7070
  annotations:
    link.argocd.argoproj.io/external-link: "https://evcc.k8s-cl01.local"

configmap:
  - name: evcc-configmap-tpl
    data:
      evcc.yaml: |
        network:
          schema: http
          host: evcc.local # .local suffix announces the hostname on MDNS
          port: 7070
        log: debug
        levels:
          cache: error
        plant: 
        sponsortoken: {{ .sponsortoken }}
        interval: 10s
        mqtt:
          broker: {{ .mqtt_broker }}
          topic: {{ .mqtt_topic }}
          clientid: {{ .mqtt_clientid }}
          user: {{ .mqtt_user }}
          password: {{ .mqtt_password }}
        meters:
        - type: custom
          name: pv
          power:
            source: mqtt
            topic: solaredge/se3680h/ac_power
            timeout: 30s
          energy:
            source: mqtt
            topic: solaredge/se3680h/ac_energy_kwh
            timeout: 30s
        - type: custom
          name: dsmr
          power:
            source: mqtt
            topic: dsmr/reading/electricity_currently_delivered
            timeout: 30s
            scale: 1000
          currents:
            - source: mqtt
              topic: dsmr/reading/phase_power_current_l1
              timeout: 30s
            - source: mqtt
              topic: dsmr/reading/phase_power_current_l2
              timeout: 30s
            - source: mqtt
              topic: dsmr/reading/phase_power_current_l3
              timeout: 30s
        chargers:
          - name: alfen
            type: template
            template: alfen
            modbus: tcpip
            id: 1
            host: 192.168.16.90
            port: 502
        vehicles:
        - name: enyaq
          type: template
          template: enyaq
          user: {{ .vehicle_enyaq_user }}
          password: {{ .vehicle_enyaq_password }}
          title: Enyaq_iV80
          capacity: 82
          timeout: 10s          
          cache: 15m
        tariffs:
          grid:
            type: template
            template: nordpool
            region: NL
            currency: EUR
            charges: 0.10154
            tax: 0.21
            formula: math.Max((price + charges) * (1 + tax) + 0.02, 0.0)
        circuits:
          - name: main
            maxCurrent: 25
            meter: dsmr
            parent: null
        loadpoints:
          - title: Home
            charger: alfen
            circuit: main
            vehicle: enyaq
            mode: off
            phases: 0
            soc:
              poll:
                mode: always
                interval: 60m
              estimate: false
        site:
          title: Home
          meters:
            grid: dsmr
            pv: pv

externalSecrets:
  - name: evcc-config-externalsecret
    storeName: hashicorp-vault
    refreshInterval: 15m
    targetName: evcc-secret
    templateName: evcc-configmap-tpl
    templateItems:
      - key: evcc.yaml
    data:
      - secretKey: mqtt_broker
        remoteRef:
          key: evcc/configmap
          property: mqtt_broker
      - secretKey: mqtt_topic
        remoteRef:
          key: evcc/configmap
          property: mqtt_topic
      - secretKey: mqtt_clientid
        remoteRef:
          key: evcc/configmap
          property: mqtt_clientid
      - secretKey: mqtt_user
        remoteRef:
          key: evcc/configmap
          property: mqtt_user
      - secretKey: mqtt_password
        remoteRef:
          key: evcc/configmap
          property: mqtt_password
      - secretKey: vehicle_enyaq_user
        remoteRef:
          key: evcc/configmap
          property: vehicle_enyaq_user
      - secretKey: vehicle_enyaq_password
        remoteRef:
          key: evcc/configmap
          property: vehicle_enyaq_password
      - secretKey: entsoe_securitytoken
        remoteRef:
          key: evcc/configmap
          property: entsoe_securitytoken
      - secretKey: sponsortoken
        remoteRef:
          key: evcc/configmap
          property: sponsortoken
      - secretKey: messaging_pushover_app
        remoteRef:
          key: evcc/configmap
          property: messaging_pushover_app
      - secretKey: messaging_pushover_device
        remoteRef:
          key: evcc/configmap
          property: messaging_pushover_device

pvc:
  - name: evcc-data
    size: 10Gi
    storageClassName: nfs-subdir-prod

httproute:
  name: evcc-httproute
  hostnames:
    - evcc.k8s-cl01.local
  parentRef:
    name: services
    namespace: ns-op-gateway-services
    sectionName: https
       remoteRef:
          key: evcc/configmap
          property: entsoe_securitytoken
      - secretKey: sponsortoken
        remoteRef:
          key: evcc/configmap
          property: sponsortoken
      - secretKey: messaging_pushover_app
        remoteRef:
          key: evcc/configmap
          property: messaging_pushover_app
      - secretKey: messaging_pushover_device
        remoteRef:
          key: evcc/configmap
          property: messaging_pushover_device

pvc:
  - name: evcc-data
    size: 10Gi
    storageClassName: nfs-subdir-prod

httproute:
  name: evcc-httproute
  hostnames:
    - evcc.k8s-cl01.local
  parentRef:
    name: services
    namespace: ns-op-gateway-services
    sectionName: https
