---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: node-red
  namespace: argocd 
  labels:
    component: applications
    function: home-automation
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  source:
    repoURL: https://github.com/TheIronRock95/homelab-kube-cluster.git
    path: applications/node-red
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: node-red
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true