# installs additional argocd components to enable gitops for argocd and other operators
# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

  # argocd crds + installation (bootstrap)
resources:
- argocd-namespace.yaml
- argocd-application.yaml
- argocd-projects.yaml
- argocd-repositories.yaml
- argocd-external-secrets.yaml
- argocd-httproute.yaml
- operators/
- applications/
- https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.14.2

patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: argocd-application-controller
    path: patches/patch-argocd-application-controller.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-applicationset-controller
    path: patches/patch-argocd-applicationset-controller.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-dex-server
    path: patches/patch-argocd-dex-server.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-notifications-controller
    path: patches/patch-argocd-notifications-controller.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-redis
    path: patches/patch-argocd-redis.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-repo-server
    path: patches/patch-argocd-repo-server.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-server
    path: patches/patch-argocd-server.yaml
  - path: patches/patch-argocd-clusterrole.yaml
  - path: patches/patch-argocd-cm.yaml
  - path: patches/patch-argocd-cmd-params-cm.yml
  - path: patches/patch-argocd-rbac-cm.yaml
