name: Lint and Scan Kubernetes Resources

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  trivy:
    name: Trivy Config Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: yamls
          format: json
          output: trivy-report.json
          severity: CRITICAL,HIGH

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json